---
os: linux
dist: xenial
language: python
python: "3.8"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git
install:
  - pip install ansible
  - git clone https://github.com/bfmartin/ansible-sshknownhosts.git library/sshknownhosts
script:
  - echo localhost > inventory
  - ln -s ansible-ssh ../weareinteractive.ssh
  - ansible-playbook --version
  - ansible-playbook --syntax-check -i inventory tests/main.yml
  - ansible-playbook -i inventory tests/main.yml --connection=local --become -vvvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
