---

- import_tasks: vars.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-vars

- import_tasks: install.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-install

- import_tasks: config.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-config

- include_tasks: known_hosts.yml
  when: ssh_known_hosts | length > 0
  tags:
    - system
    - networking
    - ssh
    - ssh-known-hosts

- import_tasks: service.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-service
