---

- name: Including OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      errors: ignore
      files:
        - "{{ ansible_facts.distribution | lower }}/{{ ansible_facts.distribution_release }}.yml"
        - "{{ ansible_facts.distribution | lower }}.yml"
      paths:
        - 'vars'
